<?php
if(!isset($CONFIG))$_CONFIG=[];
$_CONFIG['db']=[
        'host'=>'nagyzcom.ipagemysql.com',
        'user'=>'learn',
    'password'=>'malaguti94',
          'db'=>'learn',
     'charset'=>'utf8'
    ];
?>